# Generated by Django 5.0.3 on 2024-03-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0003_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pict',
            field=models.ImageField(upload_to='category'),
        ),
    ]
