# Generated by Django 5.0.3 on 2024-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0005_alter_movie_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pict',
            field=models.ImageField(upload_to='movieposter'),
        ),
    ]
