# Generated by Django 5.0.3 on 2024-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0006_alter_movie_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pict',
            field=models.ImageField(default='default.jpg', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pict',
            field=models.ImageField(default='default.jpg', upload_to='movieposter'),
        ),
    ]
